### ISSUE TITLE
Captured Pokemon doesn't work

### ISSUE THREAD

**Issue by suguru03** [Tr8rStudios/pokemongo_map#9]
Hi, I'm just looking for like this map for Canada and it looks good!
I tried to post captured Pokemon, but it didn't work.
How can I post the data?

<img width="435" alt="screen shot 2016-07-13 at 12 47 38 pm" src="https://cloud.githubusercontent.com/assets/8013633/16817632/7dc85aa4-48f8-11e6-9f54-2d4618fe6972.png">

**Comment by ericjiang97** [comment]
@suguru03. We've just fixed it.

**Comment by suguru03** [comment]
Thanks :)
